### ISSUE TITLE
Algorithm.getResult Represent?

### ISSUE THREAD

**Issue by Vance-Turner** [jMetal/jMetalDocumentation#11]
What does [getResults](http://jmetal.github.io/jMetal/apidocs/org/uma/jmetal/algorithm/multiobjective/nsgaii/NSGAII.html#getResult--) represent? Are those the solutions on the Pareto front across all generations? The number written out from SolutionListOutput doesn't seem to match either the number of generations or population size.

**Comment by ajnebro** [comment]
That method returns the final solutions found by an algorithm, usually the final population or swarm, but that depends on the algorithm. For example, SMPSO and MOCell return an external archive instead of the swarm/population. 

Anyway, just take a look to the algorithms you are using. In the case of NSGA-II, in the jMetal 5 version it returns the non-dominated solutions of the final population. 

The idea is that you can change the method according to your needs. For example, when dealing with contrained problems, that method is usually modified to return only feasible solutions.

**Comment by Vance-Turner** [comment]
Thank-you for the explanation! I am currently using NSGA-II.
